name: iOS starter workflow

on:
  push:
    branches: [ "ThiagoHBA-patch-1" ]
  pull_request:
    branches: [ "ThiagoHBA-patch-1" ]
    
jobs:
  run_tests:
    runs-on: macOS-latest
    strategy:
      matrix:
        include:
          - xcode: "14.1"
            ios: "16.1"
    name: test iOS (${{ matrix.ios }})
    steps:
    - uses: actions/checkout@v1
    - name: Run unit tests
      run: xcodebuild test -scheme bubble-jam -project bubble-jam.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 14,OS=${{ matrix.ios }}' | xcpretty && exit ${PIPESTATUS[0]}
